version: '3.8'

services:
  backend:
    build: ./backend-master
    container_name: laravel_backend
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:yourAppKeyHere
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test_db
      - DB_USERNAME=test_user
      - DB_PASSWORD=test_pass
    volumes:
      - ./backend-master:/var/www/html
    depends_on:
      - db

  frontend:
    build: ./frontend-master
    container_name: nuxt_frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend-master:/usr/src/app

  db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_PASSWORD: test_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

